//! FIX 4.4 session layer.
//!
//! * [`Session`] — sans-IO state machine (logon, heartbeats, TestRequest timeouts,
//!   sequence numbers, gap detection, ResendRequest / gap-fill SequenceReset, logout).
//! * [`MessageStore`] — persistent seq numbers + outbound journal
//!   ([`MemoryStore`], [`FileStore`]).
//! * [`run_session`] — tokio driver over any byte stream (TCP; TLS behind `tls`).

pub mod session;
pub mod store;
pub mod transport;

#[cfg(feature = "tls")]
pub mod tls;

pub use session::{Action, Role, Session, SessionConfig, State};
pub use store::{FileStore, MemoryStore, MessageStore};
pub use transport::{run_session, SessionCommand, SessionEvent};

#[derive(Debug, thiserror::Error)]
pub enum SessionError {
    #[error("i/o: {0}")]
    Io(#[from] std::io::Error),
    #[error("encode: {0}")]
    Encode(#[from] fix_codec::EncodeError),
    #[error("framing: {0}")]
    Framing(fix_codec::DecodeError),
    #[error("session not logged on")]
    NotLoggedOn,
    #[error("administrative messages are generated by the session itself")]
    AdminViaApp,
}
